### ISSUE TITLE
scribe-tool license?

### ISSUE THREAD

**Issue by BigBlueHat** [json-ld/minutes#2]
This mostly looks like the work of one, @gkellogg. 😉 

It'd be great to get a license on this and possibly even (eventually) give it's own repo and distribute it via npm (all of which I'd be happy to help with).

For now, though, it'd be great to http://choosealicense.org/ 😄 

Thanks!
🎩

**Comment by gkellogg** [comment]
Actually, it’s Manu’s tool that I’ve tweeked a bit. Takes some handholding, but has some nice features.

**Comment by gkellogg** [comment]
@msporny, care to opine?

**Comment by gkellogg** [comment]
Perhaps the [W3C Software and Document License](https://www.w3.org/Consortium/Legal/copyright-software) would cover it:

> All documents in this Repository are licensed by contributors under the [W3C Software and Document License](https://www.w3.org/Consortium/Legal/copyright-software).

It was copied from https://github.com/opencreds/minutes/blob/master/LICENSE, so that may be the one to use. It's @msporny's creation, so he decides.

**Comment by msporny** [comment]
It was/is CC-0... 3-clause BSD is fine as well. I'd rather not do W3C SDL.

If either of you don't like CC-0, let's do 3-clause BSD.

**Comment by BigBlueHat** [comment]
@msporny does/did it have it's own repo? It'd be nice to just pull the tool in via package.json (vs. maintaining code with the archives)--and obviously I'd tweak the code to use templates per-the local repo or some such. 😄 

License choices are of course fine, though I'm curious (tangentially) why *not* the W3C SDL (but totally fine if this code is not under that license).

**Comment by BigBlueHat** [comment]
And, if we get scrawl it's own repo, I'll make PRs to this one and opencreds to get them using a package.json originated scrawl command line thingie.

Cheers!
🎩

**Comment by msporny** [comment]
> @msporny does/did it have it's own repo? 

Nope, it has 3! (note that the W3C CCG also uses the tool)

> It'd be nice to just pull the tool in via package.json (vs. maintaining code with the archives)--and obviously I'd tweak the code to use templates per-the local repo or some such. 

Yeah, that'd be nice. It has been a constant work in progress over the past decade or so. Note instructions on using it:

https://github.com/w3c-ccg/w3c-ccg.github.io/blob/master/irc_ref.md#publishing-the-minutes

It's a part of a larger system... :)

> License choices are of course fine, though I'm curious (tangentially) why not the W3C SDL (but totally fine if this code is not under that license).

Developers don't know CC-0 and W3C SDL well enough to feel comfortable with it, thus the 3-clause BSD license.

**Comment by BigBlueHat** [comment]
@msporny works for me!
